#!/bin/bash

mkdir -p tmp

sass templates/style.scss tmp/style.css
node build_html.mjs cards_3x3_a4 delmbach coin_piles

mkdir -p dist/delmbach
weasyprint tmp/coin_piles.html dist/delmbach/coin_piles.pdf