#!/bin/bash

mkdir -p tmp

sass templates/style.scss tmp/style.css

# A4 3x3

# export SHEET=npc_heroes
export SHEET=goblins
node build_html.mjs cards_3x3_a4 delmbach $SHEET

# A4 2x2

# sass templates/style_2x2_a4.scss tmp/style_2x2_a4.css
# export SHEET=npc_heroes
# node build_html.mjs cards_2x2_a4 delmbach $SHEET

mkdir -p dist/delmbach
weasyprint tmp/${SHEET}.html dist/delmbach/${SHEET}.pdf